version: '3.8'

services:
  llm-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-proxy
    restart: unless-stopped
    # ports:
    #   - 11434:11434
    # volumes:
    #   # Mount config file
    #   - ./config.json:/app/config/config.json:ro
    #   # Mount database directory (allows persistence)
    #   - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11434/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

